# MkDocs configuration for default Material-themed build
INHERIT: mkdocs-base.yml

site_url: https://docs.percona.com/percona-operator-for-mysql/pxc/

plugins:
  section-index: {}

theme:
  name: material
  custom_dir: _resourcepdf/overrides
# Theme features
  features:
    - search.highlight
    - navigation.top
    - navigation.tracking
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - content.code.copy

